"""empty message

Revision ID: 5a539f91c77c
Revises: 81539996c2d2
Create Date: 2018-08-25 19:53:32.582423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a539f91c77c'
down_revision = '81539996c2d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('start_playoffs', sa.Date(), nullable=True))
    op.drop_column('seasons', 'end_regular_season')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('end_regular_season', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('seasons', 'start_playoffs')
    # ### end Alembic commands ###
