"""empty message

Revision ID: 81539996c2d2
Revises: 553844615928
Create Date: 2018-08-24 17:58:59.842924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81539996c2d2'
down_revision = '553844615928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_regular_season', sa.Date(), nullable=True),
    sa.Column('end_playoffs', sa.Date(), nullable=True),
    sa.Column('cap_floor', sa.Float(), nullable=True),
    sa.Column('cap_ceiling', sa.Float(), nullable=True),
    sa.Column('games', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Date(), nullable=True),
    sa.Column('overall_selected', sa.Integer(), nullable=True),
    sa.Column('round_selected', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home', sa.Boolean(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signing_bonus', sa.Integer(), nullable=True),
    sa.Column('base_salary', sa.Integer(), nullable=True),
    sa.Column('max_performance_bonus', sa.Integer(), nullable=True),
    sa.Column('minors_salary', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('contract', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['season'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('toi', sa.Float(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('sv_percentage', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_game_id'], ['team_games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contracts', sa.Column('sign_date', sa.Date(), nullable=True))
    op.drop_column('contracts', 'start_date')
    op.drop_column('contracts', 'years')
    op.add_column('players', sa.Column('country_born', sa.String(), nullable=True))
    op.add_column('players', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('players', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('height_cm', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.drop_column('players', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('players', 'weight_kg')
    op.drop_column('players', 'last_name')
    op.drop_column('players', 'height_cm')
    op.drop_column('players', 'first_name')
    op.drop_column('players', 'dob')
    op.drop_column('players', 'country_born')
    op.add_column('contracts', sa.Column('years', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('contracts', 'sign_date')
    op.drop_table('player_games')
    op.drop_table('contract_seasons')
    op.drop_table('team_games')
    op.drop_table('employments')
    op.drop_table('draft_picks')
    op.drop_table('seasons')
    op.drop_table('games')
    # ### end Alembic commands ###
